MTDSA-19408: Validator Improvements for individuals-charges-api
hmrc/individuals-charges-api pull request #152
Opened 2023-10-02 07:49 UTC by GazalNebHMRC

2023-10-02 11:01 UTC, SamuelJacobsHMRC requested changes

2023-10-02 14:13 UTC, GazalNebHMRC commented on test/api/controllers/ControllerSpecHateoasSupport.scala
> +  val hateoaslinks: Seq[Link] = Seq(hateoas.Link(href = "/foo/bar", method = GET, rel = "test-relationship"))
Making it private is causing compilation errors.

2023-10-03 09:56 UTC, SamuelJacobsHMRC requested changes

2023-10-03 09:56 UTC, SamuelJacobsHMRC commented on .sbtopts
> +-J-Xmx3G
This file still needs removing

2023-10-03 09:56 UTC, SamuelJacobsHMRC commented on test/v2/controllers/validators/RetrievePensionChargesValidatorFactorySpec.scala
> +    // invalid nino
comments in this file can be removed

2023-10-03 09:56 UTC, SamuelJacobsHMRC commented on app/v1/controllers/validators/AmendPensionChargesRulesValidator.scala
> +  private val pensionSchemeTaxRefRegex = "^\\d{8}[R]{1}[a-zA-Z]{1}$"
```suggestion
  private val qropsRefRegex            = "^[Q]{1}[0-9]{6}$".r
  private val pensionSchemeTaxRefRegex = "^\\d{8}[R]{1}[a-zA-Z]{1}$".r
```

(to convert from string to regex)

2023-10-03 09:56 UTC, SamuelJacobsHMRC commented on app/v1/controllers/validators/AmendPensionChargesRulesValidator.scala
> +        s"/pensionSavingsTaxCharges/benefitInExcessOfLifetimeAllowance/amount"),
lot's of strings starting with `s"..."` but no string interpolation being done so can be removed

2023-10-03 10:01 UTC, GazalNebHMRC commented on .sbtopts
> +-J-Xmx3G
I added this to gitignore

2023-10-03 10:15 UTC, SamuelJacobsHMRC approved these changes

2023-10-03 10:30 UTC, merged