MTDSA-27951
hmrc/individuals-charges-api pull request #174
Opened 2024-12-17 17:03 UTC by benryan1790

2024-12-27 10:39 UTC, EdCope requested changes

2024-12-27 10:39 UTC, EdCope commented on app/config/ChargesFeatureSwitches.scala
>    */
CL102 feature flag is no longer used. Probably should remove from the configs

2024-12-27 10:39 UTC, EdCope commented on it/config/DocumentationControllerISpec.scala
File and package can be removed

2024-12-31 13:16 UTC, DavouJ approved these changes

2024-12-31 13:17 UTC, merged